name: Gambler NFL Scan
on:
  schedule:
    - cron: '30 13 * * 4'   # Thu 09:30 ET (TNF)
    - cron: '00 13 * * 7'   # Sun 09:00 ET (main slate)
  workflow_dispatch: {}
jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy
      - name: Run Gambler NFL scan
        env:
          GAMBLER_SEASON: "2025"
          GAMBLER_WEEK: "1"
          GAMBLER_SIMS: "50000"
        run: |
          python scripts/gambler_scan_nfl.py
      - name: Commit broadcast to signals/
        run: |
          git config user.name "signals-bot"
          git config user.email "signals-bot@users.noreply.github.com"
          git add signals/*.json || true
          git commit -m "chore(gambler-nfl): update signals latest + weekly payload" || echo "No changes"
          git push
